---
author: Nurettin Åenyer
description: Folyolar
email: seyyah@bil.omu.edu.tr
url: fo.seyyah.me
domain: seyyah.me
brand: default
intro: ''
googleanalytics: ''
googleplus: ''
landslide: /usr/bin/landslide
css: _/default.css
js: _/default.js
